#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-thoughtbot-shoulda
Version  : 2.11.1
Release  : 7
URL      : https://rubygems.org/downloads/thoughtbot-shoulda-2.11.1.gem
Source0  : https://rubygems.org/downloads/thoughtbot-shoulda-2.11.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-thoughtbot-shoulda-bin
BuildRequires : ruby
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc

%description
The Shoulda test suite (in particular - the tests that test shoulda)
Quick overview:

%package bin
Summary: bin components for the rubygem-thoughtbot-shoulda package.
Group: Binaries

%description bin
bin components for the rubygem-thoughtbot-shoulda package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n thoughtbot-shoulda-2.11.1
gem spec %{SOURCE0} -l --ruby > rubygem-thoughtbot-shoulda.gemspec

%build
gem build rubygem-thoughtbot-shoulda.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
thoughtbot-shoulda-2.11.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/thoughtbot-shoulda-2.11.1 && rake --trace test TESTOPTS="-v" && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/thoughtbot-shoulda-2.11.1.gem
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/CONTRIBUTION_GUIDELINES.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/MIT-LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/bin/convert_to_should_syntax
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/action_controller.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/action_controller/macros.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/action_controller/matchers.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/action_controller/matchers/assign_to_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/action_controller/matchers/filter_param_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/action_controller/matchers/redirect_to_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/action_controller/matchers/render_template_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/action_controller/matchers/render_with_layout_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/action_controller/matchers/respond_with_content_type_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/action_controller/matchers/respond_with_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/action_controller/matchers/route_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/action_controller/matchers/set_session_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/action_controller/matchers/set_the_flash_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/action_mailer.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/action_mailer/assertions.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/action_mailer/matchers.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/action_mailer/matchers/have_sent_email.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/active_record.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/active_record/assertions.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/active_record/helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/active_record/macros.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/active_record/matchers.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/active_record/matchers/allow_mass_assignment_of_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/active_record/matchers/allow_value_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/active_record/matchers/association_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/active_record/matchers/ensure_inclusion_of_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/active_record/matchers/ensure_length_of_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/active_record/matchers/have_db_column_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/active_record/matchers/have_db_index_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/active_record/matchers/have_readonly_attribute_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/active_record/matchers/validate_acceptance_of_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/active_record/matchers/validate_format_of_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/active_record/matchers/validate_numericality_of_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/active_record/matchers/validate_presence_of_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/active_record/matchers/validate_uniqueness_of_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/active_record/matchers/validation_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/assertions.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/autoload_macros.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/context.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/integrations/rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/integrations/rspec2.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/integrations/test_unit.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/macros.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/private_helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/proc_extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/rails.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/tasks.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/tasks/list_tests.rake
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/tasks/yaml_to_shoulda.rake
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/lib/shoulda/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/rails/init.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/README
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/fail_macros.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/fixtures/addresses.yml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/fixtures/friendships.yml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/fixtures/posts.yml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/fixtures/products.yml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/fixtures/taggings.yml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/fixtures/tags.yml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/fixtures/users.yml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/functional/posts_controller_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/functional/users_controller_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/matchers/action_mailer/have_sent_email_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/matchers/active_record/allow_mass_assignment_of_matcher_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/matchers/active_record/allow_value_matcher_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/matchers/active_record/association_matcher_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/matchers/active_record/ensure_inclusion_of_matcher_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/matchers/active_record/ensure_length_of_matcher_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/matchers/active_record/have_db_column_matcher_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/matchers/active_record/have_db_index_matcher_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/matchers/active_record/have_readonly_attributes_matcher_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/matchers/active_record/validate_acceptance_of_matcher_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/matchers/active_record/validate_format_of_matcher_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/matchers/active_record/validate_numericality_of_matcher_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/matchers/active_record/validate_presence_of_matcher_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/matchers/active_record/validate_uniqueness_of_matcher_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/matchers/controller/assign_to_matcher_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/matchers/controller/filter_param_matcher_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/matchers/controller/redirect_to_matcher_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/matchers/controller/render_template_matcher_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/matchers/controller/render_with_layout_matcher_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/matchers/controller/respond_with_content_type_matcher_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/matchers/controller/respond_with_matcher_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/matchers/controller/route_matcher_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/matchers/controller/set_session_matcher_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/matchers/controller/set_the_flash_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/other/autoload_macro_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/other/context_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/other/convert_to_should_syntax_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/other/helpers_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/other/private_helpers_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/other/should_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_model_builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/controllers/application_controller.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/controllers/posts_controller.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/controllers/users_controller.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/helpers/application_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/helpers/posts_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/helpers/users_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/models/address.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/models/flea.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/models/friendship.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/models/notifier.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/models/pets/cat.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/models/pets/dog.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/models/post.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/models/product.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/models/profile.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/models/registration.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/models/tag.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/models/tagging.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/models/treat.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/models/user.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/views/layouts/posts.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/views/layouts/users.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/views/layouts/wide.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/views/notifier/the_email.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/views/posts/edit.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/views/posts/index.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/views/posts/new.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/views/posts/show.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/views/users/edit.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/views/users/index.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/views/users/new.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/app/views/users/show.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/config/boot.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/config/database.yml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/config/environment.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/config/environments/test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/config/initializers/new_rails_defaults.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/config/initializers/shoulda.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/config/routes.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/db/migrate/001_create_users.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/db/migrate/002_create_posts.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/db/migrate/003_create_taggings.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/db/migrate/004_create_tags.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/db/migrate/005_create_dogs.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/db/migrate/006_create_addresses.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/db/migrate/007_create_fleas.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/db/migrate/008_create_dogs_fleas.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/db/migrate/009_create_products.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/db/migrate/010_create_friendships.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/db/migrate/011_create_treats.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/db/migrate/20090506203502_create_profiles.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/db/migrate/20090506203536_create_registrations.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/db/migrate/20090513104502_create_cats.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/db/schema.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/public/404.html
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/public/422.html
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/public/500.html
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/script/console
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/script/generate
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/test/shoulda_macros/custom_macro.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/vendor/gems/gem_with_macro-0.0.1/shoulda_macros/gem_macro.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_root/vendor/plugins/plugin_with_macro/shoulda_macros/plugin_macro.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails2_test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_model_builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/README
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/controllers/application_controller.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/controllers/posts_controller.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/controllers/users_controller.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/helpers/application_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/models/address.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/models/flea.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/models/friendship.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/models/notifier.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/models/pets/cat.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/models/pets/dog.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/models/post.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/models/product.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/models/profile.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/models/registration.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/models/tag.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/models/tagging.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/models/treat.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/models/user.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/views/layouts/application.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/views/layouts/posts.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/views/layouts/users.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/views/layouts/wide.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/views/notifier/the_email.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/views/posts/edit.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/views/posts/index.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/views/posts/new.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/views/posts/show.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/views/users/edit.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/views/users/index.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/views/users/new.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/app/views/users/show.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/config.ru
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/config/application.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/config/boot.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/config/database.yml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/config/environment.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/config/environments/development.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/config/environments/production.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/config/environments/test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/config/initializers/backtrace_silencers.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/config/initializers/inflections.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/config/initializers/mime_types.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/config/initializers/secret_token.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/config/initializers/session_store.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/config/locales/en.yml
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/config/routes.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/db/migrate/001_create_users.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/db/migrate/002_create_posts.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/db/migrate/003_create_taggings.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/db/migrate/004_create_tags.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/db/migrate/005_create_dogs.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/db/migrate/006_create_addresses.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/db/migrate/007_create_fleas.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/db/migrate/008_create_dogs_fleas.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/db/migrate/009_create_products.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/db/migrate/010_create_friendships.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/db/migrate/011_create_treats.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/db/migrate/20090506203502_create_profiles.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/db/migrate/20090506203536_create_registrations.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/db/migrate/20090513104502_create_cats.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/db/seeds.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/public/404.html
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/public/422.html
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/public/500.html
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/public/favicon.ico
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/public/images/rails.png
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/public/index.html
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/public/javascripts/application.js
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/public/javascripts/controls.js
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/public/javascripts/dragdrop.js
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/public/javascripts/effects.js
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/public/javascripts/prototype.js
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/public/javascripts/rails.js
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/public/robots.txt
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/script/rails
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/test/performance/browsing_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_root/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rails3_test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/rspec_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/unit/address_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/unit/cat_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/unit/dog_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/unit/flea_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/unit/friendship_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/unit/post_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/unit/product_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/unit/tag_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/unit/tagging_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/thoughtbot-shoulda-2.11.1/test/unit/user_test.rb
/usr/lib64/ruby/gems/2.3.0/specifications/thoughtbot-shoulda-2.11.1.gemspec

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/convert_to_should_syntax
